const category_data = [
    {
        cat_id: "1",
        cat_name: "men"
    },
    {
        cat_id: "2",
        cat_name: "women"
    },
    {
        cat_id: "3",
        cat_name: "kids"
    }
];

const subcategory_data = [
    {
        cat_id: "1",
        sub_cat_id: "101",
        sub_cat_name: "t-shirts"
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        sub_cat_name: "jeans"
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        sub_cat_name: "shoes"
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        sub_cat_name: "jacket"
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        sub_cat_name: "accessories"
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        sub_cat_name: "sarees"
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        sub_cat_name: "top"
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        sub_cat_name: "jeans"
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        sub_cat_name: "shoes"
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        sub_cat_name: "jewellery"
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        sub_cat_name: "clouths"
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        sub_cat_name: "toys"
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        sub_cat_name: "school stationery"
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        sub_cat_name: "shoes"
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        sub_cat_name: "winter wear"
    },
];

const Product_data = [
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1151",
        product_name:"Kalapuri Women's Ready To Wear Nauwari Silk Saree Without Blouse Piece",
        product_description: "Traditional Readymade Nauvari Saree, Matching borders for blouse sleeves || Material: Belgaum Catlon || Size: Height 40 Inch, Hip size suitable for 34-42 Inch || Easy to wear and Comfortable like Salwar.",
        product_rating: "3.5",
        product_rating_count: "101",
        product_img: "https://m.media-amazon.com/images/I/61eY2UrLGCL._SX679._SX._UX._SY._UY_.jpg",
        product_price: "3,599",
        product_discount_price: "1,799",
        product_discount_percenteage: "50%",
        product_color: "Yellow",
        product_size: "Regular fit",
        recentrly_view: true,
        trending_product: true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1152",
        product_name:"Pandadi Saree Women's Paithani Silk Saree With unstitched Blouse Piece", 
        product_description: "Saree Fabric : Art Silk || Saree Length :6.3 Mtrs Including Blouse (5.5 mts+ 80 cm Blouse ).",
        product_rating:"3.9",
        product_rating_count:"53",
        product_img: "https://m.media-amazon.com/images/I/91hQBa9RUbL._UY879_.jpg",
        product_price: "2,999",
        product_discount_price: "1,499",
        product_discount_percenteage: "50%",
        product_color:"Pink-orange",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1153",
        product_name:"Sidhidata Women's Kanjivaram Saree With Blouse Piece",
        product_description:"Care Instructions: Machine Wash || Saree Fabric : Banarasi Silk || Saree Length : 6.3 Mtr included Blouse Piece || Work Type : Woven Floral design All over / Soft Finished /Comfortable to wear",
        product_rating:"4.5",
        product_rating_count:"758",
        product_img: "https://m.media-amazon.com/images/I/91HAgnw2CTL._UX679_.jpg",
        product_price: "895",
        product_discount_price: "895",
        product_discount_percenteage: "0%",
        product_color:"Pink",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1154",
        product_name:"Sidhidata Textile Women's Dola Silk Foil Printed Saree With Unstitched Blouse Piece",
        product_description:"Care Instructions: hand wash || Fabric : Dola Silk || Type : Foil Printed || Design : Leheriya || Saree Length : 5.5 Mtr + Blouse Length : 0.80 Mtr (Unstitched)",
        product_rating:"3.5",
        product_rating_count:"234",
        product_img: "https://m.media-amazon.com/images/I/710Gqx1n91L._UY879_.jpg",
        product_price: "2,999",
        product_discount_price: "749",
        product_discount_percenteage: "75%",
        product_color:"Rama Green",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1155",
        product_name:"Sidhidata Women's Full Crushed/Pleated Satin Saree With Unstitched Blouse Piece",
        product_description:"Care Instructions: hand wash || Fabric : Heavy Satin || Type : Crushed/ Pleated Saree || Design : Plain/Solid || Saree Length : 5.6 Mtr + Blouse Length : 0.80 Mtr (Unstitched)",
        product_rating:"4.1",
        product_rating_count:"652",
        product_img: "https://m.media-amazon.com/images/I/71+1MFT-tvL._UX679_.jpg",
        product_price: "2,499.00",
        product_discount_price: "599.00",
        product_discount_percenteage: "76%",
        product_color:"Dark Green",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1156",
        product_name:"L G FASHION Womens Lycra Ready To Wear Saree with UnStitched Blouse",
        product_description:"Ready To Wear Saree || Length : Saree Length is 5.5 Meter With UnStitched Blouse. There might be minor colour variation between actual product and image shown on screen due to lighting on the photography",
        product_rating:"3.3",
        product_rating_count:"14",
        product_img: "https://m.media-amazon.com/images/I/71w5gCBq7OL._SY879._SX._UX._SY._UY_.jpg",
        product_price: "2,199.00",
        product_discount_price: "799.00",
        product_discount_percenteage: "64%",
        product_color:"Grey",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1157",
        product_name:"Indian Youth Women's Net Saree With Blouse Piece",
        product_description:"Saree Length: 5.50 Mtr || Blouse Length: 0.80 Mtr || Saree Fabric: Georgette || Blouse: Banglory Beautifully applique Work Self style Saree || Occasion : Casual & festive || fashionable latest design Beautifully Women Saree Multi colors",
        product_rating:"3.6",
        product_rating_count:"19",
        product_img: "https://m.media-amazon.com/images/I/812nLExAIvS._UY879_.jpg",
        product_price: "4,999.00",
        product_discount_price: "1,000.00",
        product_discount_percenteage: "80",
        product_color:"Red",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1158",
        product_name:"Market Magic World Women's Satin Silk Shiny Saree with Brocade Blouse (FreeSize_More Color Available)",
        product_description:"Saree length: 5.50 m || Blouse length: 0.90 m || content - 1 saree with 1 blouse piece",
        product_rating:"3.9",
        product_rating_count:"704",
        product_img: "https://m.media-amazon.com/images/I/71pMN2t0nnL._UY879_.jpg",
        product_price: "899.00",
        product_discount_price: "499.00",
        product_discount_percenteage: "44%",
        product_color:"Black",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1159",
        product_name:"Kiaaron Women's Ikat Hand Block Print Jaipuri Cotton Mulmul Saree with Blouse Piece",
        product_description:"Beautiful Traditional Ethnic Indian Wear Saree with Blouse Piece. This Saree gives an Ethnic Indian look. This sari is great for wearing purposes. Work: Printed, Block print, Traditional Ethnic Look",
        product_rating:"4.3",
        product_rating_count:"325",
        product_img: "https://m.media-amazon.com/images/I/31jzFQLaWfL.jpg",
        product_price: "6,999.00",
        product_discount_price: "799.00",
        product_discount_percenteage: "89%",
        product_color:"Yellow & black",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1160",
        product_name:"Shivanya Handicrafts Women's Hand block printed cotton mulmul fabric saree With Blouse Piece",
        product_description:"Beautiful Traditional Ethnic Indian Wear Saree with Blouse Piece .This Saree gives Ethnic Indian look. This sari is great for wearing purpose.",
        product_rating:"4",
        product_rating_count:"319",
        product_img: "https://m.media-amazon.com/images/I/713qMkLcfoS._UX679_.jpg",
        product_price: "2,799.00",
        product_discount_price: "799.00",
        product_discount_percenteage: "71%",
        product_color:"White 4",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1161",
        product_name:"Lymio Women's Regular Top",
        product_description:"Care Instructions: Dry Clean Only || Fabric : Chiffon ||Sleeve Type : 3/4th Sleeve",
        product_rating:"4.5",
        product_rating_count:"477",
        product_img: "https://m.media-amazon.com/images/I/61CD7jRIVRL._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "389.00",
        product_discount_price: "1,799.00",
        product_discount_percenteage: "74%",
        product_color:"Green",
        product_size:"Regular fit",
        recentrly_view:true, 
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1162",
        product_name:"Wedani Women's Casual Puff Sleeves Ruffled Collor Foral Top",
        product_description:"Fabric: Rayon||Sleeve Type: Short Sleeve || Collar Style: Classic Collar",
        product_rating:"3",
        product_rating_count:"216",
        product_img: "https://m.media-amazon.com/images/I/71sm8MRnZ2L._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "259.00",
        product_discount_price: "1,299.00",
        product_discount_percenteage: "80%",
        product_color:"Dark-Pink",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1163",
        product_name:"Aahwan Women's & Girls' Solid Asymmetrical Neck Cotton Rib Cut Out Crop Top",
        product_description:"Care Instructions: Machine Wash || Material: 95% Cotton 5% Polyester || Sleeve: Sleeveless",
        product_rating:"4",
        product_rating_count:"177",
        product_img: "https://m.media-amazon.com/images/I/7192ExRoKWL._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "329.00",
        product_discount_price: "999.00",
        product_discount_percenteage: "67%",
        product_color:"Beige",
        product_size:"Slim fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1164",
        product_name:"Rajovati Women Puff Sleeve Tops",
        product_description:"Care Instructions: hand wash only || Fabric :Made of high quality Cotton Lycra Blend",
        product_rating:"4",
        product_rating_count:"234",
        product_img: "https://m.media-amazon.com/images/I/51G5HkHfmOL._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "379.00",
        product_discount_price: "1999.00",
        product_discount_percenteage: "81%",
        product_color:"White",
        product_size:"Slim fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1165",
        product_name:"SIGHTBOMB Ribbed Polo Collar Extended Sleeves Tops for Women",
        product_description:"Care Instructions: Machine wash",
        product_rating:"4",
        product_rating_count:"979",
        product_img: "https://m.media-amazon.com/images/I/51tcflY-fNL._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "420.00",
        product_discount_price: "1200.00",
        product_discount_percenteage: "65%",
        product_color:"White",
        product_size:"Slim fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1166",
        product_name:"AELOMART Women's Top(AWT6088-P_Yellow)",
        product_description:"Care Instruction:wash only separately||Fabric :100% Cotton fabric",
        product_rating:"4",
        product_rating_count:"55",
        product_img: "https://m.media-amazon.com/images/I/71K3zXFkxDL._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "399.00",
        product_discount_price: "1599.00",
        product_discount_percenteage: "75%",
        product_color:"Yellow",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1167",
        product_name:"hasmi Casual Square Neck Full Sleeves Western Stylish Women's Tops",
        product_description:"Care Instructions: Machine Wash||Materials: 95% Polyester, 5% Spandex; stretchable fabric || Sleeve:long sleeve|| Neck Type:square neck",
        product_rating:"3.5",
        product_rating_count:"424",
        product_img: "https://m.media-amazon.com/images/I/71ooEN04ZHL._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "349.00",
        product_discount_price: "1599.00",
        product_discount_percenteage: "78%",
        product_color:"Black",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1168",
        product_name:"Dream Beauty Fashion Bishop Sleeves Square Neck Slim Top Polyester Blend",
        product_description:"Care Instructions: Hand Wash Only|| Sleeves : Bishop||Neck:Square",
        product_rating:"4.5",
        product_rating_count:"61",
        product_img: "https://m.media-amazon.com/images/I/41CxywOyyML._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "299.00",
        product_discount_price: "799.00",
        product_discount_percenteage: "63%",
        product_color:"Frost White",
        product_size:"Slim fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1169",
        product_name:" SIRIL Women's Crepe Printed Top",
        product_description:"Care Instructions: Machine Wash||Fabric : Crepe | Inner Fabric||work: printed||Sleeve:Sleeveless ",
        product_rating:"4",
        product_rating_count:"29",
        product_img: "https://m.media-amazon.com/images/I/71TNhGWphrL._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "349.00",
        product_discount_price: "1230.00",
        product_discount_percenteage: "72%",
        product_color:"Multicolour",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
     {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1170",
        product_name:"AELOMART Women's Top(AWT6044-Pn_Multicolour)",
        product_description:"Care Instructions: Machine Wash ||Neck: Square",
        product_rating:"4",
        product_rating_count:"305",
        product_img: "https://m.media-amazon.com/images/I/611E1a7ZM5L._AC_UL480_FMwebp_QL65_.jpg",
        product_price: "399.00",
        product_discount_price: "1599.00",
        product_discount_percenteage: "75%",
        product_color:"Multicolour",
        product_size:"Regular fit",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1181",
        product_name:"Centrino 5631 Casual-Men's Shoes",
        product_description:"CENTRINO CASUAL SHOES MATERIAL: SYNTHETIC MATERIAL. THESE SHOES ARE MADE UP OF HIGH QUALITY SYNTHETIC MATERIAL STAYS STRONG AND DURABLE - MEANING THE SHOES WILL LAST MUCH LONGER. LIFESTYLE: FORMAL / BUSINESS. PAIR THESE STYLISH CENTRINO SHOES WITH YOUR SHIRT & TROUSERS FOR THAT PERFECT LOOK. OFFICE WEAR, OFFICE SHOES, FORMAL SHOES, SLIP-ON, BUSINESS SHOES. CLOSURE: SLIP-ON. CENTRINO SHOES ARE HAND-CRAFTED FOR THAT PERFECT FIT. PERFORATED INSOLE LETS AIR PASS THROUGH THE MATERIAL. THIS IS GREAT FOR LEATHER SHOES BECAUSE THE MATERIAL LETS AIR IN TO COOL YOUR FEET AND STOP THEM FROM SMELLING. FIT: COMFORT FIT. CENTRINO ENDORSES STYLE THAT STRIKES A FINE BALANCE BETWEEN THE CLASSIC AND THE MODERN, THE DISCREET AND THE BOLD WITH GOOD TASTE BEING THE ONLY CRITERION FOR SELECTION. CARE INSTRUCTIONS: ALLOW YOUR PAIR OF SHOES TO AIR ON A REGULAR BASIS. THIS HELPS THEM RETAIN THEIR NATURAL SHAPE; DRY SHOES AT ROOM TEMPERATURE ONLY. EXCESSIVE EXPOSURE TO SUN, WILL CAUSE THE LEATHER TO SHRINK, WRINKLE, HARDEN, DRY, AND CRACK. USE SHOE BAGS TO PREVENT ANY STAINS OR MILDEW; DUST ANY DRY DIRT FROM THE SURFACE USING A CLEAN CLOTH. FOR MENS",
        product_rating:"4.0",
        product_rating_count:"675",
        product_img: "https://m.media-amazon.com/images/I/71fj3YjhqoL._UY695_.jpg",
        product_price: "1799",
        product_discount_price: "799",
        product_discount_percenteage: "56",
        product_color:"Blue",
        product_size:"9UK",
        recentrly_view:true,
        trending_product:true,
    },


    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1182",
        product_name:"FLITE Men's Flip Flop",
        product_description:"Sparx Presents footwear range that Will Keep Your Feet At Great Ease, While You walk, run or work out in the Gym. These Are Light In Weight, Flexible And Very Comfortable To Wear As Well.",
        product_rating:"3.0",
        product_rating_count:"500",
        product_img: "https://m.media-amazon.com/images/I/91RIz6UeU0L._UY695_.jpg",
        product_price: "800",
        product_discount_price: "400",
        product_discount_percenteage: "50",
        product_color:"Blue",
        product_size:"7UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1183",
        product_name:"ASIAN Men's Wonder-13 Sports Running Shoes",
        product_description:"Exclusive design and durable materials every step feels light and breezy. Breathable, free-moving fabrics which adjust according to your foot and creates an astoundingly easy-going experience.",
        product_rating:"4.0",
        product_rating_count:"500",
        product_img: "https://m.media-amazon.com/images/I/61Uh7P5bIUL._SY695._SX._UX._SY._UY_.jpg",
        product_price: "1000",
        product_discount_price: "499",
        product_discount_percenteage: "50",
        product_color:"Black",
        product_size:"8UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1184",
        product_name:"ASIAN Men's Running Shoes for Men I Sport Shoes for Boys with Beads Technology Sole for Extra Jump I Memory Foam Insole Casual Shoes for Men",
        product_description:"The outsoles are made by an air cushion, doubling the effect of shock absorption. Besides, these shoes perform excellent in durability and are also slip resistant. It provides push cushioning comfort for foot pain relief and helps relieve pressure while conforming to your every step",
        product_rating:"4.0",
        product_rating_count:"807",
        product_img: "https://m.media-amazon.com/images/I/617Gd+HQQQL._UY695_.jpg",
        product_price: "2000",
        product_discount_price: "999",
        product_discount_percenteage: "50",
        product_color:"White",
        product_size:"8UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1185",
        product_name:"ASIAN Men's Running Shoes for Men I Sport Shoes for Boys with Beads Technology Sole for Extra Jump I Memory Foam Insole Casual Shoes for Men",
        product_description:"The outsoles are made by an air cushion, doubling the effect of shock absorption. Besides, these shoes perform excellent in durability and are also slip resistant. It provides push cushioning comfort for foot pain relief and helps relieve pressure while conforming to your every step",
        product_rating:"4.0",
        product_rating_count:"807",
        product_img: "https://m.media-amazon.com/images/I/71+8xHNsdHL._UX695_.jpg",
        product_price: "2000",
        product_discount_price: "999",
        product_discount_percenteage: "50",
        product_color:"White",
        product_size:"8UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1186",
        product_name:"Neeman's ReLive Knit Casual Lace Up Sneakers for Men | Padded Insole for Extra Support, Stylish Shoes for Boys",
        product_description:"Elevate your style with this classy pair of Casual Shoe from the house of ZOVIM brand. Featuring a contemporary refined design with exceptional comfort, this pair is perfect to give your quintessential dressing an upgrade.",
        product_rating:"4.5",
        product_rating_count:"2345",
        product_img: "https://m.media-amazon.com/images/I/71IxVUq8HTL._SX695._SX._UX._SY._UY_.jpg",
        product_price: "3299",
        product_discount_price: "2639",
        product_discount_percenteage: "20",
        product_color:"Red",
        product_size:"9UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1186",
        product_name:"ROCKFIELD Men's Blue Denim Sneakers Casual Shoes",
        product_description:"Elevate your style with this classy pair of Casual Shoe from the house of ZOVIM brand. Featuring a contemporary refined design with exceptional comfort, this pair is perfect to give your quintessential dressing an upgrade.",
        product_rating:"4.0",
        product_rating_count:"779",
        product_img: "https://m.media-amazon.com/images/I/81E0uiZHnOL._UY695_.jpg",
        product_price: "1499",
        product_discount_price: "749",
        product_discount_percenteage: "50",
        product_color:"Blue",
        product_size:"8UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1186",
        product_name:"Zovim Men's Casual Shoes",
        product_description:"Elevate your style with this classy pair of Casual Shoe from the house of ZOVIM brand. Featuring a contemporary refined design with exceptional comfort, this pair is perfect to give your quintessential dressing an upgrade.",
        product_rating:"4.0",
        product_rating_count:"779",
        product_img: "https://m.media-amazon.com/images/I/81UKVfIck-L._UX695_.jpg",
        product_price: "3895",
        product_discount_price: "2726",
        product_discount_percenteage: "30",
        product_color:"Blue",
        product_size:"8UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1187",
        product_name:"Woodland Boys Moccasins",
        product_description:"Genuine leather Casual products.",
        product_rating:"4.0",
        product_rating_count:"999",
        product_img: "https://m.media-amazon.com/images/I/71wbf76WYPL._UX695_.jpg",
        product_price: "3995",
        product_discount_price: "2596",
        product_discount_percenteage: "30",
        product_color:"Black",
        product_size:"9UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1188",
        product_name:"Zovim Men's Casual Shoeseeken Black Canvas Lightweight Casual Shoes for Men (by Paragon)",
        product_description:"A pair of high ankle classic chukka canvas shoe is the best companion to be worn at college festivals; while jumping puddles & while running away from then mundane. Glide through the week in India's first lightweight canvas shoes. Goes well with Jeans / Denims",
        product_rating:"4.0",
        product_rating_count:"999",
        product_img: "https://m.media-amazon.com/images/I/615VR2lCp5L._UY695_.jpg",
        product_price: "1499",
        product_discount_price: "1275",
        product_discount_percenteage: "15",
        product_color:"Gray",
        product_size:"9UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1189",
        product_name:"The diamond-encrusted Tom Ford shoes were worn by Nick Cannon on America's Got Talent.",
        product_description:"The most expensive shoes in the world are their own rightful category in the luxury market. Often sold off at auctions rather than at retailers, these shoes are much more than footwear. The most expensive shoes can be a slice of history or even require a safe to be stored in",
        product_rating:"5.0",
        product_rating_count:"21789",
        product_img: "https://footwearnews.com/wp-content/uploads/2019/02/diamond_loafers-1.jpg",
        product_price: "159147000",
        product_discount_price: "158147000",
        product_discount_percenteage: "2",
        product_color:"Silver",
        product_size:"9UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1190",
        product_name:"Michael Jordan’s Air Jordan 12s",
        product_description:"The sneakers once belonged to former Chicago Bulls player Michael Jordan. The all-star basketball player wore the shoes during the famous Flu Game",
        product_rating:"5.0",
        product_rating_count:"1456",
        product_img: "https://footwearnews.com/wp-content/uploads/2016/05/air-jordan-12-flu-game-1.jpg",
        product_price: "8336517",
        product_discount_price: "7935673",
        product_discount_percenteage: "5",
        product_color:"Red",
        product_size:"9UK",
        recentrly_view:true,
        trending_product:true,
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1191",
        product_name:"Azai By Nykaa ",
        product_description:" This Green Jewellery Colored Stone Set by Azai is all you need to get the spotlight on you at any wedding you step into. The set includes a necklace and a pair of earrings.",
        product_rating:"4.9",
        product_rating_count:"11223",
        product_img: "https://m.media-amazon.com/images/I/41kOJDFXLNL._UY695_.jpg",
        product_price: "4563",
        product_discount_price: "1,597",
        product_discount_percenteage: "65%",
        product_color:"Golden",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1192",
        product_name:"Azai By Nykaa Fashion Latest Silver & Mint Green Jewellery Set For Women",
        product_description:" This Green Jewellery Colored Stone Set by Azai is all you need to get the spotlight on you at any wedding you step into. The set includes a necklace and a pair of earrings.Team it up with a gorgeous and elegant saree paired with heels and you will be the ultimate showstopper wherever you go.",
        product_rating:"4.7",
        product_rating_count:"2727",
        product_img: "https://m.media-amazon.com/images/I/61GaOnu4Z+L._UY695_.jpg",
        product_price: "2,849.00",
        product_discount_price: "997",
        product_discount_percenteage: "65%",
        product_color:"Silver",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1193",
        product_name:"Harshitha's Jewelry Metal Women's Bangles(HRSTJ004_P)",
        product_description:"This product is made by Women entrepreneurs from Tamil Nadu who are part of Amazon Saheli program",
        product_rating:"4.1",
        product_rating_count:"12897",
        product_img: "https://m.media-amazon.com/images/I/61zjuf+rygL._UY575_.jpg",
        product_price: "599.00",
        product_discount_price: "499.00",
        product_discount_percenteage: "17% ",
        product_color:"	Multicolor",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1194",
        product_name:"Brado Jewellery Rose Gold Plated American Diamond Black Duck Necklace Golden Chain for Women & Girls (Yellow)",
        product_description:" Brado Jewellery is renowned by its classic and playful designs.Choose the divine jewelry to express your love with us. A perfect gift for your soul mate. The Perfect touch of sparkle. Brado Jewellery Necklace is a classic piece that never goes out of style. This solitaire Necklace is a simple, shiny treat that you will wear forever. A perfect gift on the occasions like Wedding, Valentine’s day, Birthdays etc.",
        product_rating:"3.0",
        product_rating_count:"2234",
        product_img: "https://m.media-amazon.com/images/I/71upm73OSlS._UY575_.jpg",
        product_price: "₹999",
        product_discount_price: "119.00",
        product_discount_percenteage: "88%",
        product_color:"White",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1195",
        product_name:"Yobella",
        product_description:"Never allow your fashion jewellery to come in contact with harsh chemicals, oils, nor spray perfumes directly on them. This will cause the jewellery to fade, discolour, or even ruin them completely. And we wouldn’t want that!",
        product_rating:"3.0",
        product_rating_count:"234",
        product_img: "https://m.media-amazon.com/images/I/710dnChlpcS._UY695_.jpg",
        product_price: "1,999.00",
        product_discount_price: "197.00",
        product_discount_percenteage: "90%",
        product_color:"Multicolor",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1196",
        product_name:"YouBella Jewellery Silver and Gold Stylish Adjustable Bracelet Combo of Two for Girls and Women",
        product_description:"Never allow your fashion jewellery to come in contact with harsh chemicals, oils, nor spray perfumes directly on them. This will cause the jewellery to fade, discolour, or even ruin them completely. And we wouldn’t want that!",
        product_rating:"3.9",
        product_rating_count:"232434",
        product_img: "https://m.media-amazon.com/images/I/61-FgEVebgL._UY575_.jpg",
        product_price: "1,199.00",
        product_discount_price: "245.00",
        product_discount_percenteage: "80%",
        product_color:"Golden and silver",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1197",
        product_name:"MMTC-PAMP 24k (999.9) 10 gm Goddess Lakshmi Yellow Gold Coin",
        product_description:"999.9 / 24K PUREST GOLD: Crafted from 999.9 / 24K purest gold, this gold coin goes through rigorous refining and purification process to ensure you get the purest piece of metal. We go beyond 999.9 to give you 999.9+ purity",
        product_rating:"4.5",
        product_rating_count:"23192",
        product_img: "https://m.media-amazon.com/images/I/71LLiqiFh6L._UY575_.jpg",
        product_price: "65,960.00",
        product_discount_price: "56,120.00",
        product_discount_percenteage: "15%",
        product_color:"Gold",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1198",
        product_name:"Shining Diva Fashion 18k Gold and Silver Plated Adjustable Crystal Cuff Bracelet for Women and Girls",
        product_description:"Shining diva is a well known brand across fashion jewellery sector shining diva products are preferred by many designers, stars and celebrities shining diva fashion jewelry believes in making beauty and fashion a part of everybody's life",
        product_rating:"3.8",
        product_rating_count:"92892",
        product_img: "https://m.media-amazon.com/images/I/714fIkdqr7L._UY575_.jpg",
        product_price:  "₹1,999.00",
        product_discount_price: "299.00",
        product_discount_percenteage: "85%",
        product_color:"Other Color",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1199",
        product_name:"Yellow Chimes Swarovski Elements Deep Ocean Love Hearts Bracelet for Women and Girls",
        product_description:"This Soft Blue Swarovski Crystal Special collection Hearts Joining Bangle radiates feminine romance. Shimmering in clear crystal pavé, it is embellished with a sparkling Blue Hearts, It is good to add moods to Love, and beauty to any Outfit. The adjustable closure ensures a secure fit. The Oval shape of bracelet keep the main part in front and even makes it stick to hand perfectly. The diameter is between 5-6 cm.",
        product_rating:"3.4",
        product_rating_count:"23871",
        product_img: "https://m.media-amazon.com/images/I/61Yi-0OfYDL._UY575_.jpg",
        product_price: " ₹5,999.00",
        product_discount_price: "1,499.00",
        product_discount_percenteage: "75%",
        product_color:"Blue",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1120",
        product_name:"GANESHAGEMS (इक्क्क्क़ मुखी रुद्राक्ष) Genuine Color Nepali Beads 21 Mukhi Rudraksha Original Certified by Reputed Lab for Men & Women",
        product_description:"Twenty One Face Rudraksha Is Also Known As Kubera Rudraksha.",
        product_rating:"4.1",
        product_rating_count:"12324",
        product_img: "https://m.media-amazon.com/images/I/41lbuBlxLLL.jpg",
        product_price: "2,62,000.00",
        product_discount_price: "₹1,31,000.00",
        product_discount_percenteage: "50%",
        product_color:"Brown",
        product_size:"NA",
        recentrly_view:true,
        trending_product:true
    }
]

